# The markdown files here ARE the product: canonical license texts whose
# wording and layout are fixed once published, so lint is tuned to the
# canonical format instead of ignoring the license files. The format's
# summary tables and Required Notice arrive with each versioned text, so
# the tuning below stays load-bearing even when no version file trips a
# rule at the moment:
# - MD013: off; fleet markdown prose is one source line per paragraph,
#   and a published text's line breaks are canonical whatever their width.
# - MD034: the Required Notice line embeds a bare URL.
# - MD060: the summary tables pad their cells but keep a tight |---|
#   delimiter row, matching no single recognized column style.
config:
  MD013: false
  MD034: false
  MD060: false

globs:
  - "**/*.md"
